---
name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14', '12', '10' ]
    name: Node.js ${{ matrix.node-version }}
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
