---
name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14', '12', '10' ]
    name: Node.js ${{ matrix.node-version }}
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and test @carnesen/cli
      working-directory: ./main
      run: |
        npm ci
        npm test
        npm pack
    - name: Build and test @carnesen/cli-examples
      working-directory: ./examples
      run: |
        npm ci
        npm install ../main/carnesen-cli*.tgz
        npm test
        npm pack
    - name: Build and test @carnesen/cli-website
      working-directory: ./website
      run: |
        npm ci
        npm install ../main/carnesen-cli*.tgz
        npm install ../examples/carnesen-cli*.tgz
        npm test
