---
name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '16', '14', '12' ]
    name: Node.js ${{ matrix.node-version }}
    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test @carnesen/cli
      working-directory: ./packages/cli
      run: |
        npm ci
        npm test

    - name: Build and test @carnesen/cli-examples
      working-directory: ./packages/cli-examples
      run: |
        npm ci
        npm install ../cli/carnesen-cli*.tgz
        npm test

    - name: Build and test @carnesen/cli-website
      working-directory: ./packages/cli-website
      run: |
        npm ci
        npm install ../cli/carnesen-cli*.tgz
        npm install ../cli-examples/carnesen-cli*.tgz
        npm test

    - name: Build and test @carnesen/cli-website-server
      working-directory: ./packages/cli-website-server
      run: |
        npm ci
        npm install ../cli/docs/carnesen-cli*.tgz
        npm install ../cli-website/carnesen-cli*.tgz
        npm test
